//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace t1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.ATTRIBUTE = new HashSet<ATTRIBUTE>();
        }
    
        public decimal INTERNAL_ITEM_NUM { get; set; }
        public string ITEM1 { get; set; }
        public string COMPANY { get; set; }
        public string ITEM_DESC { get; set; }
        public string STORAGE_TEMPLATE { get; set; }
        public string ITEM_CLASS { get; set; }
        public string PACKING_CLASS { get; set; }
        public string ATTRIBUTE_TRACK { get; set; }
        public Nullable<decimal> DAYS_TO_EXPIRE { get; set; }
        public string LOCATING_RULE { get; set; }
        public string ALLOCATION_RULE { get; set; }
        public string REPLENISHMENT_RULE { get; set; }
        public string EMPTY_LOC_RULE { get; set; }
        public string ITEM_CATEGORY1 { get; set; }
        public string ITEM_CATEGORY2 { get; set; }
        public string ITEM_CATEGORY3 { get; set; }
        public string ITEM_CATEGORY4 { get; set; }
        public string ITEM_CATEGORY5 { get; set; }
        public string ITEM_CATEGORY6 { get; set; }
        public string ITEM_CATEGORY7 { get; set; }
        public string ITEM_CATEGORY8 { get; set; }
        public string USER_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string ACTIVE { get; set; }
        public string ATTRIBUTE_TEMPLATE_NAME { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
        public Nullable<decimal> SERIAL_NUM_TRACK { get; set; }
        public string SERIAL_NUM_TEMPLATE_NAME { get; set; }
        public string BRAND { get; set; }
        public string DIVISION { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string ITEM_SIZE { get; set; }
        public string ITEM_COLOR { get; set; }
        public string ITEM_STYLE { get; set; }
        public Nullable<decimal> LIST_PRICE { get; set; }
        public Nullable<decimal> NET_PRICE { get; set; }
        public string PLACE_OF_ORIGIN { get; set; }
        public string ITEM_ATTRIBUTE1 { get; set; }
        public string ITEM_ATTRIBUTE2 { get; set; }
        public string ITEM_ATTRIBUTE3 { get; set; }
        public string ITEM_ATTRIBUTE4 { get; set; }
        public string ITEM_ATTRIBUTE5 { get; set; }
        public string ITEM_ATTRIBUTE6 { get; set; }
        public string ITEM_ATTRIBUTE7 { get; set; }
        public string ITEM_ATTRIBUTE8 { get; set; }
        public string MAINTAIN_STS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRIBUTE> ATTRIBUTE { get; set; }
    }
}
