//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace t1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_UNIT_OF_MEASURE
    {
        public decimal INTERNAL_ITEM_UM { get; set; }
        public string ITEM { get; set; }
        public string COMPANY { get; set; }
        public decimal SEQUENCE { get; set; }
        public string QUANTITY_UM { get; set; }
        public decimal CONVERSION_QTY { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string DIMENSION_UM { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string WEIGHT_UM { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
        public Nullable<decimal> TREAT_FULL_PCT { get; set; }
        public string MOVEMENT_CLS { get; set; }
        public string ITEM_CLASS { get; set; }
        public string TREAT_AS_LOOSE { get; set; }
        public string GROUP_DURING_CHECKIN { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
    }
}
